---
title: "Pokemon -- Visualizing Variables"
output: html_document
---

Read the data
```{r read file}
pokedat <- read.csv("../pokemon/pokemon.csv", header = T)
```

Exploring the data with Basic plots
```{r data plots}
ggplot(pokedat, aes(pokedat$Type.1)) + geom_bar(aes(fill = as.factor(pokedat$Type.1))) + 
  scale_fill_discrete(name="Pokemon Types",
                      labels=c( "Bug","Dark","Dragon","Electric","Fairy","Fighting","Fire","Flying","Ghost","Grass","Ground",
                                "Ice","Normal","Poison","Psychic","Rock","Steel","Water")) + 
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  labs(x= "Type 1",y= "Frequency" , title = "Pokemon Types")

ggplot(pokedat, aes(pokedat$Type.2)) + geom_bar(aes(fill = as.factor(pokedat$Type.2))) + 
  scale_fill_discrete(name="Pokemons of Double Type",
                      labels=c("Doesn't Have","Bug","Dark","Dragon","Electric","Fairy","Fighting","Fire","Flying","Ghost","Grass","Ground",
                                "Ice","Normal","Poison","Psychic","Rock","Steel","Water")) + 
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  labs(x= "Type 1",y= "Frequency" , title = "Pokemons of Double Type")

ggplot(pokedat, aes(pokedat$Total)) + geom_histogram(binwidth=4, colour="black", fill="green") +
  labs(x= "Total",y= "Frequency" , title = "Plot of Total Pokemon Score")

ggplot(pokedat, aes(pokedat$HP)) + geom_histogram(binwidth=4, colour="black", fill="green") +
  labs(x= "Health",y= "Frequency" , title = "Plot of Pokemon Health")

ggplot(pokedat, aes(pokedat$Attack)) + geom_histogram(binwidth=4, colour="black", fill="green") +
  labs(x= "Attack",y= "Frequency" , title = "Plot of Pokemon Attack Rating")  

ggplot(pokedat, aes(pokedat$Defense)) + geom_histogram(binwidth=4, colour="black", fill="green") +
  labs(x= "Defense",y= "Frequency" , title = "Plot of Pokemon Defense Rating")

ggplot(pokedat, aes(pokedat$Sp..Atk)) + geom_histogram(binwidth=4, colour="black", fill="green") +
  labs(x= "Special Attack",y= "Frequency" , title = "Plot of Pokemon Special Attack Rating")

ggplot(pokedat, aes(pokedat$Sp..Def)) + geom_histogram(binwidth=4, colour="black", fill="green") +
  labs(x= "Special Defense",y= "Frequency" , title = "Plot of Pokemon Special Defense Rating")   

ggplot(pokedat, aes(pokedat$Speed)) + geom_histogram(binwidth=4, colour="black", fill="green") +
  labs(x= "Speed",y= "Frequency" , title = "Plot of Pokemon Speed")
```

5. 10 Best Pokemons in each category.
 5.1 Higher Total - 10 pokemons with Higher Total Score
```{r}
head(pokedat[order(pokedat$Total,decreasing = TRUE), ], n = 10)
```
 5.2 Higher Health
```{r}
head(pokedat[order(pokedat$HP,decreasing = TRUE), ], n = 10)
```
 5.3 Higher Attack
```{r}
head(pokedat[order(pokedat$Attack,decreasing = TRUE), ], n = 10)
```
 5.4 Higher Defense
```{r}
head(pokedat[order(pokedat$Defense,decreasing = TRUE), ], n = 10)
```
 5.5 Higher Special Attack
```{r}
head(pokedat[order(pokedat$Sp..Atk,decreasing = TRUE), ], n = 10)
```
 5.6 Higher Special Defense
```{r}
head(pokedat[order(pokedat$Sp..Def,decreasing = TRUE), ], n = 10)
```
 5.7 Faster
```{r}
head(pokedat[order(pokedat$Speed ,decreasing = TRUE), ], n = 10)
```